INSERT INTO books (id, author, name, price) VALUES
                                   (1,'Gabriel García Márquez', 'One Hundred Years of Solitude', '5'),
                                   (2,'Harper Lee', 'To Kill a Mockingbird', '10'),
                                   (3,'F. Scott Fitzgerald', 'The Great Gatsby', '8'),
                                   (4,'Dan Brown', 'The Da Vinci Code', '5'),
                                   (5,'Jane Austen', 'Pride and Prejudice', '5'),
                                   (6,'Agatha Christie', 'And Then There Were None', '7'),
                                   (7,'Douglas Adams', 'The Hitchhiker''s Guide to the Galaxy', '5'),
                                   (8,'Ernest Hemingway', 'The Old Man and the Sea', '10'),
                                   (9,'Albert Camus', 'The Stranger', '6'),
                                   (10,'Alice Sebold', 'The Lovely Bones', '5'),
                                   (11,'J. R. R. Tolkien', 'The Lord of the Rings 1', '5'),
                                   (12,'J. R. R. Tolkien', 'The Lord of the Rings 2', '5'),
                                   (13,'J. R. R. Tolkien', 'The Lord of the Rings 3', '5'),
                                   (14,'J. R. R. Tolkien', 'The Hobbit', '8'),
                                   (15,'J. R. R. Tolkien', 'The Silmarillion', '10'),
                                   (16,'Ursula Le Guin', 'Planet of Exile', '6'),
                                   (17,'Ursula Le Guin', 'City of Illusions', '5'),
                                   (18,'Ursula Le Guin', 'The Dispossessed', '10'),
                                   (19,'Ursula Le Guin', 'The Left Hand of Darkness', '5'),
                                   (20,'Lewis Carroll', 'Alice''s Adventures in Wonderland', '7'),
                                   (21,'Charles Dickens', 'A Tale of Two Cities', '10'),
                                   (22,'Umberto Eco', 'The Name of the Rose', '5'),
                                   (23,'J. P. Donleavy', 'The Ginger Man', '8'),
                                   (24,'V. C. Andrews', 'Flowers in the Attic', '5'),
                                   (25,'Carl Sagan', 'Cosmos', '5');
ALTER TABLE books AUTO_INCREMENT = 26;